[build]
publish = "dist/"
command = "bun run build"

[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = ["node_modules/.astro"]

[[redirects]]
from = "https://dammaretz.netlify.app/*"
to = "/:splat"
status = 301

[[headers]]
for = "/*"
[headers.values]
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
X-DNS-Prefetch-Control = "on"
X-XSS-Protection = "1; mode=block"
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"
cache-control = "max-age=604800"

[[headers]]
for = "/*.woff2"
[headers.values]
cache-control = "public, max-age=31536000, immutable"
